export { CONFIG_FILENAME, CONFIG_VERSION, DEFAULT_ACTION, SYMLINK_POLICY, type GuardAction, type SymlinkPolicy } from "./config/constants.js";
export type { GuardConfig, GuardRule, LoadedGuardConfig, ValidationIssue, ValidationResult } from "./config/types.js";
export { GuardConfigError, loadGuardConfig } from "./config/load.js";
export { validateGuardConfig } from "./config/validate.js";
export { GuardPathError, canonicalizeTargetPath } from "./core/paths.js";
export { GuardRequestError, prepareOperationRequest } from "./core/request.js";
export type { GuardDecision, OperationRequest, PreparedOperationRequest } from "./core/types.js";
export { evaluateOperation } from "./core/evaluate.js";
export { evaluateHostOperation } from "./host/adapter.js";
export { HOST_FAILURE_STAGE, type EvaluateHostOperationOptions, type HostEvaluationResult, type HostFailureStage, type HostOperationInput } from "./host/types.js";
